import React, { useEffect, useMemo, useRef, useState } from 'react';
import { MapContainer, Marker, Polyline, TileLayer, useMap } from 'react-leaflet';
import L from 'leaflet';
import {
  ArrowLeft, BookOpen, CalendarDays, Check, ChevronDown, FileDown, Map as MapIcon,
  MapPin, Pencil, Printer, Route, Settings, SlidersHorizontal, Sparkles, X
} from 'lucide-react';
import 'leaflet/dist/leaflet.css';
import './crew-maps.css';
import { supabase } from '../supabase';

const HUB_URL = import.meta.env.VITE_HUB_URL || 'https://www.taylorscout.com';
const BUDGET_URL = import.meta.env.VITE_BUDGET_URL || 'https://budget.taylorscout.com';
const BIBLE_URL = import.meta.env.VITE_BIBLE_URL || 'https://bible.taylorscout.com';
const CALENDAR_URL = import.meta.env.VITE_CALENDAR_URL || 'https://calendar.taylorscout.com';
const MAP_TYPES = ['CREW','PREP / STRIKE','GRIP & ELECTRIC','TRUCKS','BACKGROUND','SHOOT DAY','CUSTOM'];
const DEFAULT_ORIGINS = [
  {id:'westside',name:'Westside / Santa Monica',lat:34.0195,lng:-118.4912},
  {id:'westvalley',name:'West Valley / Hollywood',lat:34.1016,lng:-118.3267},
  {id:'eastvalley',name:'East Valley',lat:34.1478,lng:-118.1445}
];
const uid=()=>crypto.randomUUID();
const fmtDate=v=>{if(!v)return '';const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})};
const dateRange=e=>{const a=e?.shootStart||'',b=e?.shootEnd||a;return a?(a===b?fmtDate(a):`${fmtDate(a)} – ${fmtDate(b)}`):''};
function link(base,show,extra={}){const u=new URL(base,window.location.origin);u.searchParams.set('show',show.id);u.searchParams.set('showId',show.id);u.searchParams.set('showName',show.name||'');Object.entries(extra).forEach(([k,v])=>{if(v)u.searchParams.set(k,v)});return u.toString()}
function dashboardUrl(show){return `/?show=${encodeURIComponent(show.id)}&showId=${encodeURIComponent(show.id)}&showName=${encodeURIComponent(show.name||'')}`}
function WaypointMark(){return <span className="cm-mark"><svg viewBox="0 0 74 92" aria-hidden="true"><path d="M37 3C18 3 5 17 5 36c0 22 17 40 32 53 15-13 32-31 32-53C69 17 56 3 37 3Z"/><path d="M16 39l15-13 8 7 10-10 12 14-12-8-10 10-8-7-15 7Z"/><path d="M19 69c12-14 24-18 31-27-3 14-12 22-20 31l7 8-9 2-9-14Z"/></svg><span><b>TAYLOR SCOUT</b><small>CREW MAPS</small></span></span>}
function mapPinIcon(label,color='#e64545'){return L.divIcon({className:'cm-leaflet-icon',html:`<div class="cm-map-pin" style="--pin:${color}">${label}</div>`,iconSize:[32,32],iconAnchor:[16,16]})}
function FitBounds({points}){const map=useMap();useEffect(()=>{const valid=(points||[]).filter(Boolean);if(valid.length===1)map.setView(valid[0],15);else if(valid.length>1)map.fitBounds(valid,{padding:[35,35]});},[map,JSON.stringify(points)]);return null}
function deepFind(obj,terms){if(!obj||typeof obj!=='object')return null;const wanted=terms.map(x=>x.toLowerCase());const walk=(value,key='')=>{if(value==null)return null;if(typeof value==='string'&&wanted.some(t=>key.toLowerCase().includes(t))&&value.trim())return value.trim();if(Array.isArray(value)){for(const v of value){const hit=walk(v,key);if(hit)return hit}return null}if(typeof value==='object'){for(const [k,v] of Object.entries(value)){if(typeof v==='string'&&wanted.some(t=>k.toLowerCase().includes(t))&&v.trim())return v.trim();const hit=walk(v,k);if(hit)return hit}}return null};return walk(obj)}
function addressFromBible(record,kind){const exact=kind==='parking'?['crewParkingAddress','crew_parking_address','parkingAddress','parking_address']:kind==='basecamp'?['basecampAddress','base_camp_address']:['address'];for(const k of exact){const hit=deepFind(record,[k]);if(hit)return hit}return null}
function textFromBible(record,terms){return deepFind(record,terms)||''}
async function geocode(address){if(!address)return null;try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(address)}`,{headers:{'Accept-Language':'en'}});const j=await r.json();if(!j?.[0])return null;return [Number(j[0].lat),Number(j[0].lon)]}catch{return null}}
function distance(a,b){const R=6371,toRad=x=>x*Math.PI/180;const dLat=toRad(b[0]-a[0]),dLon=toRad(b[1]-a[1]),q=Math.sin(dLat/2)**2+Math.cos(toRad(a[0]))*Math.cos(toRad(b[0]))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
async function nearestHospital(point){if(!point)return null;try{const q=`[out:json][timeout:20];nwr(around:16000,${point[0]},${point[1]})[amenity=hospital];out center tags;`;const r=await fetch(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(q)}`);const j=await r.json();const rows=(j.elements||[]).map(x=>({name:x.tags?.name||'Hospital',phone:x.tags?.phone||x.tags?.['contact:phone']||'',address:[x.tags?.['addr:housenumber'],x.tags?.['addr:street'],x.tags?.['addr:city'],x.tags?.['addr:state'],x.tags?.['addr:postcode']].filter(Boolean).join(' '),point:[x.lat||x.center?.lat,x.lon||x.center?.lon]})).filter(x=>x.point[0]&&x.point[1]);rows.sort((a,b)=>distance(point,a.point)-distance(point,b.point));return rows[0]||null}catch{return null}}
function cleanInstruction(step){const m=step?.maneuver||{},name=step?.name||'';const type=m.type||'continue',mod=(m.modifier||'').replaceAll('_',' ');const dist=step?.distance||0;const d=dist>=1609?`${(dist/1609.344).toFixed(1)} mi`:dist>=305?`${(dist/1609.344).toFixed(1)} mi`:`${Math.max(50,Math.round(dist*3.28084/50)*50)} ft`;if(type==='depart')return `Head ${mod||'toward the route'} on ${name||'local streets'}`;if(type==='arrive')return 'Arrive at crew parking. Park as directed.';if(type==='merge')return `Merge ${mod||''} onto ${name}`.trim();if(type==='on ramp'||type==='off ramp')return `${type==='on ramp'?'Take the ramp':'Take the exit'} ${mod||''} ${name?`for ${name}`:''}`.trim();if(type==='turn'||type==='continue'||type==='fork'||type==='new name')return `${type==='turn'?'Turn':'Continue'} ${mod||''} ${name?`onto ${name}`:''}${dist?` for ${d}`:''}`.trim();return `${type.replaceAll('_',' ')} ${name}`.trim()}
async function routeFrom(origin,dest){if(!dest)return null;try{const url=`https://router.project-osrm.org/route/v1/driving/${origin.lng},${origin.lat};${dest[1]},${dest[0]}?overview=full&geometries=geojson&steps=true`;const r=await fetch(url);const j=await r.json();const route=j.routes?.[0];if(!route)return null;const coords=route.geometry.coordinates.map(([lng,lat])=>[lat,lng]);const steps=(route.legs?.[0]?.steps||[]).filter(s=>s.distance>25||s.maneuver?.type==='arrive').map(cleanInstruction).filter(Boolean);return {origin,coords,steps:steps.slice(0,9),distance:route.distance,duration:route.duration}}catch{return null}}
function routeLink(address){return `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(address||'')}`}
function titleFor(map){return `${map.location||'LOCATION'}${map.set?` — ${map.set}`:''}`}

export default function CrewMapsWorkspace({show,onBack}){
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[events,setEvents]=useState([]),[locations,setLocations]=useState([]),[bibles,setBibles]=useState([]),[waypoints,setWaypoints]=useState([]),[maps,setMaps]=useState([]),[settings,setSettings]=useState({signCode:'',defaultPaper:'legal',origins:DEFAULT_ORIGINS});
  const [eventId,setEventId]=useState(''),[mapType,setMapType]=useState('CREW'),[active,setActive]=useState(null),[settingsOpen,setSettingsOpen]=useState(false),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
  const event=events.find(e=>e.id===eventId)||null;
  const selectedLocation=useMemo(()=>event?locations.find(l=>l.id===event.locationId)||locations.find(l=>l.location_name===event.location)||null:null,[event,locations]);

  useEffect(()=>{let dead=false;(async()=>{setLoading(true);setError('');const [cal,loc,bib,wp,cm,st]=await Promise.all([
    supabase.from('tool_documents').select('payload').eq('show_id',show.id).eq('tool_key','calendar').maybeSingle(),
    supabase.from('production_locations').select('*').eq('show_id',show.id).order('updated_at',{ascending:false}),
    supabase.from('tool_documents').select('tool_key,payload,updated_at').eq('show_id',show.id).like('tool_key','bible-location:%'),
    supabase.from('tool_documents').select('tool_key,payload,updated_at').eq('show_id',show.id).like('tool_key','waypoint:%'),
    supabase.from('tool_documents').select('tool_key,payload,updated_at').eq('show_id',show.id).like('tool_key','crew-map:%').order('updated_at',{ascending:false}),
    supabase.from('tool_documents').select('payload').eq('show_id',show.id).eq('tool_key','crew-maps-settings').maybeSingle()
  ]);if(dead)return;const failed=[cal,loc,bib,wp,cm,st].find(x=>x.error);if(failed){setError(failed.error.message);setLoading(false);return}const payload=cal.data?.payload||{};setEvents((payload.events||[]).filter(x=>x.eventType!=='note'));setLocations((loc.data||[]).filter(x=>!x.metadata?.archived_at));setBibles(bib.data||[]);setWaypoints(wp.data||[]);setMaps((cm.data||[]).map(row=>({...row.payload,toolKey:row.tool_key,updatedAt:row.updated_at})));if(st.data?.payload)setSettings(s=>({...s,...st.data.payload,origins:st.data.payload.origins?.length?st.data.payload.origins:s.origins}));setLoading(false)})();return()=>{dead=true}},[show.id]);

  async function saveSettings(next){setSettings(next);const {data:{user}}=await supabase.auth.getUser();const {error:e}=await supabase.from('tool_documents').upsert({show_id:show.id,tool_key:'crew-maps-settings',payload:next,updated_by:user?.id||null},{onConflict:'show_id,tool_key'});if(e)setError(e.message);else setSettingsOpen(false)}
  function bibleFor(locationId){const row=bibles.find(x=>x.tool_key===`bible-location:${locationId}`);return row?.payload?.record||row?.payload||null}
  function waypointFor(locationId,calendarEventId){return waypoints.find(x=>x.payload?.context?.locationId===locationId||x.payload?.context?.calendarEventId===calendarEventId)||null}

  async function generate(){if(!event)return;setBusy(true);setStatus('Loading production information…');setError('');try{const loc=selectedLocation||{};const bible=bibleFor(loc.id||event.locationId)||{};const wp=waypointFor(loc.id||event.locationId,event.id);const locationAddress=loc.address||event.address||addressFromBible(bible,'location')||'';const parkingAddress=addressFromBible(bible,'parking')||textFromBible(bible,['crew parking'])||locationAddress;const basecampAddress=addressFromBible(bible,'basecamp')||'';setStatus('Locating map points…');const [locationPoint,parkingPoint]=await Promise.all([geocode(locationAddress),geocode(parkingAddress)]);const destination=parkingPoint||locationPoint;setStatus('Generating directions and hospital…');const [routes,hospital]=await Promise.all([Promise.all((settings.origins||DEFAULT_ORIGINS).map(o=>routeFrom(o,destination))),nearestHospital(locationPoint||destination)]);const calPayload=(await supabase.from('tool_documents').select('payload').eq('show_id',show.id).eq('tool_key','calendar').maybeSingle()).data?.payload||{};const key=calPayload.keys?.find(k=>event.keyIds?.includes(k.id))||null;const id=uid();const map={id,showId:show.id,calendarEventId:event.id,locationId:loc.id||event.locationId||'',mapType,mapType==='CUSTOM'?'CUSTOM':mapType,paper:settings.defaultPaper||'legal',episode:event.episode||loc.episode_name||'',scenes:event.scenes||loc.metadata?.scenes||'',unit:event.unit||loc.metadata?.unit||'',set:event.set||loc.set_name||'',location:event.location||loc.location_name||'Untitled Location',locationAddress,parkingAddress,basecampAddress,shootStart:event.shootStart||'',shootEnd:event.shootEnd||event.shootStart||'',prepStart:event.prepStart||'',prepEnd:event.prepEnd||'',strikeStart:event.strikeStart||'',strikeEnd:event.strikeEnd||'',signCode:settings.signCode||show.signCode||'',keyName:key?.name||show.locationManager?.name||'',keyRole:key?.role||'Key Assistant Location Manager',keyPhone:key?.phone||show.locationManager?.phone||'',warning:textFromBible(bible,['warning','crew note','parking note'])||'',locationPoint,parkingPoint,hospital,routes:routes.filter(Boolean),waypointObjects:wp?.payload?.objects||[],options:{directions:true,qr:true,sign:true,hospital:true,locationCard:true,parkingCard:true,warning:true,waypoint:true,north:true},manual:{title:'',warning:''},createdAt:new Date().toISOString()};const {data:{user}}=await supabase.auth.getUser();const {error:e}=await supabase.from('tool_documents').upsert({show_id:show.id,tool_key:`crew-map:${id}`,payload:map,revision:1,updated_by:user?.id||null},{onConflict:'show_id,tool_key'});if(e)throw e;setMaps(v=>[map,...v]);setActive(map);setStatus('Generated')}catch(e){setError(e?.message||String(e));setStatus('')}finally{setBusy(false)}}
  async function saveMap(next){setActive(next);setMaps(v=>v.map(m=>m.id===next.id?next:m));const {data:{user}}=await supabase.auth.getUser();const {error:e}=await supabase.from('tool_documents').upsert({show_id:show.id,tool_key:`crew-map:${next.id}`,payload:next,updated_by:user?.id||null},{onConflict:'show_id,tool_key'});if(e)setError(e.message)}
  const goDashboard=()=>onBack?onBack():window.location.assign(dashboardUrl(show));

  if(active)return <CrewMapEditor show={show} map={active} onBack={()=>setActive(null)} onDashboard={goDashboard} onSave={saveMap}/>;
  return <div className="cm-app"><header className="cm-topbar"><button className="cm-brand" onClick={goDashboard}><WaypointMark/></button><div className="cm-show">{show.name}</div><nav><a href={link(BUDGET_URL,show)}>Budget</a><a href={link(BIBLE_URL,show)}>Bible</a><a href={link(CALENDAR_URL,show)}>Calendar</a><a href={link(HUB_URL,show,{tool:'waypoint'})}>Waypoint</a></nav></header><main className="cm-home"><div className="cm-home-actions"><button onClick={goDashboard}><ArrowLeft size={16}/>Show Dashboard</button><button onClick={()=>setSettingsOpen(true)}><Settings size={16}/>Show Map Settings</button></div><section className="cm-intro"><small>TAYLOR SCOUT / CREW MAPS</small><h1>Generate a crew directional map</h1><p>Choose a scheduled location and map type. Crew Maps will pull the production information already entered across Taylor Scout and build the first draft for you.</p></section>{error&&<div className="cm-error">{error}</div>}
    <section className="cm-generator"><div className="cm-step"><span>1</span><label>CALENDAR / LOCATION<div className="cm-select"><select value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">Select a calendar location…</option>{events.map(e=><option key={e.id} value={e.id}>{e.location||'Untitled'} — {e.set||e.episode||'Scheduled'} — {dateRange(e)}</option>)}</select><ChevronDown size={16}/></div></label></div><div className="cm-step"><span>2</span><label>MAP TYPE<div className="cm-select"><select value={mapType} onChange={e=>setMapType(e.target.value)}>{MAP_TYPES.map(t=><option key={t}>{t}</option>)}</select><ChevronDown size={16}/></div></label></div>{event&&<div className="cm-preview"><div className="cm-preview-logo">{show.logo?<img src={show.logo} alt=""/>:<MapPin/>}</div><div><small>{event.episode||'PRODUCTION'} · {event.unit||'UNIT'}</small><b>{event.location||'Untitled Location'}</b><span>{event.set||'No set entered'}{event.scenes?` · Scenes ${event.scenes}`:''}</span><span>{selectedLocation?.address||event.address||'Address will be pulled from the shared location/Bible record'}</span><span>{dateRange(event)||'No shoot date entered'}</span></div></div>}<button className="cm-generate" disabled={!eventId||busy} onClick={generate}><Sparkles size={18}/>{busy?(status||'Generating…'):'Generate Map'}</button></section>
    <div className="cm-section-title"><div><small>SAVED MAPS</small><h2>Crew maps for this show</h2></div></div>{loading?<div className="cm-empty">Loading Crew Maps…</div>:maps.length?<div className="cm-map-list">{maps.map(m=><button key={m.id} onClick={()=>setActive(m)}><div><small>{m.mapType||'CREW MAP'}</small><b>{m.location||'Untitled Location'}</b><span>{m.set||m.episode||''} · {dateRange(m)}</span></div><Route size={18}/></button>)}</div>:<div className="cm-empty">No Crew Maps yet. Generate the first one from a calendar location.</div>}
  </main>{settingsOpen&&<SettingsModal settings={settings} show={show} onClose={()=>setSettingsOpen(false)} onSave={saveSettings}/>}</div>
}

function SettingsModal({settings,show,onClose,onSave}){const [form,setForm]=useState({...settings});return <div className="cm-modal-bg" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="cm-modal"><header><div><small>SHOW DEFAULTS</small><h2>Crew Map settings</h2><p>These are preloaded into every Crew Map for {show.name}.</p></div><button onClick={onClose}><X/></button></header><label>Yellow “LOOK FOR” sign code<input value={form.signCode||''} onChange={e=>setForm({...form,signCode:e.target.value.toUpperCase()})} placeholder="Example: TFS"/></label><label>Default print size<select value={form.defaultPaper||'legal'} onChange={e=>setForm({...form,defaultPaper:e.target.value})}><option value="legal">Legal — Landscape</option><option value="letter">Letter — Landscape</option></select></label><div className="cm-settings-note"><Check size={16}/>Show logo is pulled automatically from the active Taylor Scout show.</div><footer><button onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(form)}>Save Show Defaults</button></footer></section></div>}

function CrewMapEditor({show,map,onBack,onDashboard,onSave}){const [draft,setDraft]=useState(map),[saving,setSaving]=useState(false);const debounce=useRef(null);useEffect(()=>setDraft(map),[map.id]);function patch(p){const next={...draft,...p};setDraft(next);clearTimeout(debounce.current);debounce.current=setTimeout(async()=>{setSaving(true);await onSave(next);setSaving(false)},500)}function toggle(k){patch({options:{...draft.options,[k]:!draft.options[k]}})}const mapPoints=[draft.locationPoint,draft.parkingPoint,draft.hospital?.point,...(draft.routes||[]).flatMap(r=>r.coords?.length?[r.coords[0],r.coords[r.coords.length-1]]:[])].filter(Boolean);const qr=routeLink(draft.parkingAddress||draft.locationAddress);return <div className="cm-editor"><header className="cm-editor-top"><button className="cm-brand" onClick={onDashboard}><WaypointMark/></button><button className="cm-editor-back" onClick={onBack}><ArrowLeft size={15}/>Crew Maps</button><div className="cm-editor-title"><b>{draft.location}</b><span>{draft.mapType} · {dateRange(draft)}</span></div><span className="cm-save">{saving?'Saving…':'Saved'}</span><div className="cm-editor-actions"><select value={draft.paper||'legal'} onChange={e=>patch({paper:e.target.value})}><option value="legal">Legal Landscape</option><option value="letter">Letter Landscape</option></select><button onClick={()=>window.print()}><Printer size={15}/>Print</button></div></header><main className="cm-editor-main"><aside className="cm-controls"><div className="cm-control-head"><SlidersHorizontal size={17}/><div><small>INCLUDE ON MAP</small><b>Map contents</b></div></div>{[['directions','Directions'],['qr','Parking QR Code'],['sign','Yellow Look For Sign'],['warning','Warning Banner'],['parkingCard','Parking Card'],['locationCard','Location Card'],['hospital','Nearest Hospital'],['waypoint','Waypoint Markers'],['north','North Arrow']].map(([k,label])=><label className="cm-toggle" key={k}><input type="checkbox" checked={draft.options?.[k]!==false} onChange={()=>toggle(k)}/><span>{label}</span></label>)}<div className="cm-control-group"><small>MAP TYPE</small><input value={draft.mapType} onChange={e=>patch({mapType:e.target.value})}/><small>WARNING TEXT</small><textarea value={draft.manual?.warning??draft.warning??''} onChange={e=>patch({manual:{...draft.manual,warning:e.target.value}})} placeholder="Add an important crew warning…"/><small>YELLOW SIGN CODE</small><input value={draft.signCode||''} onChange={e=>patch({signCode:e.target.value.toUpperCase()})}/><small>KEY CONTACT</small><input value={draft.keyName||''} onChange={e=>patch({keyName:e.target.value})}/><input value={draft.keyPhone||''} onChange={e=>patch({keyPhone:e.target.value})}/></div></aside><section className={`cm-sheet ${draft.paper==='letter'?'letter':'legal'}`}>
    <div className="cm-sheet-left"><header className="cm-sheet-head"><div className="cm-show-lockup">{show.logo?<img src={show.logo} alt="Show logo"/>:<div className="cm-logo-placeholder">SHOW<br/>LOGO</div>}<div className="cm-contact"><b>{draft.keyName||'LOCATION TEAM'}</b><span>{draft.keyRole||'Key Assistant Location Manager'}</span><span>{draft.keyPhone||''}</span></div></div><div className="cm-sheet-title"><h1>{draft.manual?.title||titleFor(draft)}</h1><div className="cm-title-meta"><span>MAP IS CLOSE<br/>TO SCALE</span><b>{dateRange(draft)||'DATE TBD'}</b><strong>{draft.mapType}</strong></div></div>{draft.options?.warning!==false&&(draft.manual?.warning||draft.warning)&&<div className="cm-warning">{draft.manual?.warning||draft.warning}</div>}</header>
      <div className="cm-directions-top">{draft.options?.qr!==false&&<div className="cm-qr"><div>Aim the camera on your smart phone at the QR Code to pull up directions to <b>{draft.parkingAddress?'CREW PARKING':'LOCATION'}</b></div><img src={`https://api.qrserver.com/v1/create-qr-code/?size=170x170&data=${encodeURIComponent(qr)}`} alt="Parking QR code"/></div>}</div>{draft.options?.directions!==false&&<div className="cm-directions">{draft.routes?.length?draft.routes.map((r,i)=><section key={r.origin.id}><h3>Directions from the {r.origin.name}</h3><ol>{r.steps.map((s,j)=><li key={j}>{s}</li>)}</ol></section>):<section><h3>Directions</h3><p>Directions could not be generated automatically. Confirm the parking address and regenerate the map.</p></section>}</div>}</div>
    <div className="cm-sheet-right"><div className="cm-map-area"><MapContainer center={draft.locationPoint||draft.parkingPoint||[34.05,-118.25]} zoom={14} zoomControl={false} dragging={false} doubleClickZoom={false} scrollWheelZoom={false} boxZoom={false} keyboard={false} attributionControl={false}><TileLayer url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png"/><FitBounds points={mapPoints}/>{draft.routes?.map(r=><Polyline key={r.origin.id} positions={r.coords} pathOptions={{color:'#e3342f',weight:5,opacity:.9}}/>)}{draft.locationPoint&&<Marker position={draft.locationPoint} icon={mapPinIcon('★','#e3342f')}/>} {draft.parkingPoint&&<Marker position={draft.parkingPoint} icon={mapPinIcon('P','#2d69b3')}/>} {draft.options?.hospital!==false&&draft.hospital?.point&&<Marker position={draft.hospital.point} icon={mapPinIcon('H','#2767cf')}/>} {draft.options?.waypoint!==false&&(draft.waypointObjects||[]).filter(o=>o.points?.[0]).map(o=><Marker key={o.id} position={o.points[0]} icon={mapPinIcon((o.label||'WP').slice(0,2).toUpperCase(),o.color||'#148f86')}/>)}</MapContainer>{draft.options?.sign!==false&&<div className="cm-lookfor"><small>LOOK FOR:</small><b>{draft.signCode||'—'}</b></div>}{draft.options?.north!==false&&<div className="cm-north">▲<b>N</b></div>}</div><div className="cm-info-grid">{draft.options?.parkingCard!==false&&<article><i className="parking">P</i><b>{draft.mapType.includes('PREP')?'PREP / STRIKE PARKING':'CREW PARKING'}</b><span>{draft.parkingAddress||'Parking address not entered'}</span></article>}{draft.options?.locationCard!==false&&<article><i className="location">★</i><b>LOCATION</b><span>{draft.location}<br/>{draft.locationAddress||'Location address not entered'}</span></article>}{draft.options?.hospital!==false&&<article><i className="hospital">H</i><b>NEAREST HOSPITAL</b><span>{draft.hospital?.name||'Hospital needs confirmation'}<br/>{draft.hospital?.address||''}{draft.hospital?.phone?<><br/>{draft.hospital.phone}</>:null}</span></article>}<article className="cm-no-cars"><i>⊘</i><b>CREW NOTE</b><span>{draft.manual?.warning||draft.warning||'Follow posted crew parking and access instructions.'}</span></article></div></div>
    <footer className="cm-sheet-footer"><span>TAYLOR SCOUT · CREW MAPS</span><span>{draft.episode?`EP ${draft.episode}`:''}{draft.scenes?` · SCENES ${draft.scenes}`:''}{draft.unit?` · ${draft.unit}`:''}</span></footer></section></main></div>}
