import React,{useEffect,useMemo,useRef,useState}from'react';
import maplibregl from'maplibre-gl';
import{ArrowLeft,ChevronDown,Hand,Link2,MapPin,Minus,MousePointer2,Plus,Printer,Redo2,Save,SquareDashed,Type,Undo2}from'lucide-react';
import'maplibre-gl/dist/maplibre-gl.css';
import'./crew-maps-locked-editor.css';
import{supabase}from'../supabase';

const MAP_TYPES=['CREW','PREP / STRIKE','GRIP & ELECTRIC','TRUCKS','BACKGROUND','SHOOT DAY','CUSTOM'];
const ORIGINS=[{id:'valley',name:'Valley',lat:34.2011,lng:-118.536},{id:'westside',name:'Santa Monica / Westside',lat:34.0195,lng:-118.4912},{id:'eastside',name:'Eastside / Downtown',lat:34.0522,lng:-118.2437}];
const PALETTE=['SET','CREW PARKING','VIP PARKING','BASECAMP','CATERING','TRUCK PARKING','BG HOLDING','LUNCH','RESTROOMS','CUSTOM'];
const TRAUMA=[{name:'Providence Holy Cross Medical Center',level:'II',address:'15031 Rinaldi St, Mission Hills, CA 91345',phone:'818-365-8051'},{name:'Ronald Reagan UCLA Medical Center',level:'I',address:'757 Westwood Plaza, Los Angeles, CA 90095',phone:'310-825-9111'},{name:'Cedars-Sinai Medical Center',level:'I',address:'8700 Beverly Blvd, Los Angeles, CA 90048',phone:'310-423-3277'},{name:'LA General Medical Center',level:'I',address:'2051 Marengo St, Los Angeles, CA 90033',phone:'323-409-1000'}];
const uid=()=>crypto.randomUUID();
const fmt=v=>{if(!v)return'';const d=new Date(`${v}T12:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})};
const range=e=>{const a=e?.shootStart||'',b=e?.shootEnd||a;return a?(a===b?fmt(a):`${fmt(a)} – ${fmt(b)}`):''};
function deepFind(obj,terms){if(!obj||typeof obj!=='object')return'';const wanted=terms.map(x=>x.toLowerCase());const walk=(v,k='')=>{if(v==null)return'';if(typeof v==='string'&&wanted.some(t=>k.toLowerCase().includes(t))&&v.trim())return v.trim();if(Array.isArray(v)){for(const x of v){const r=walk(x,k);if(r)return r}}else if(typeof v==='object'){for(const[k2,x]of Object.entries(v)){if(typeof x==='string'&&wanted.some(t=>k2.toLowerCase().includes(t))&&x.trim())return x.trim();const r=walk(x,k2);if(r)return r}}return''};return walk(obj)}
async function geocode(address){if(!address)return null;try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=us&q=${encodeURIComponent(address)}`,{headers:{'Accept-Language':'en'}});const j=await r.json();return j?.[0]?[+j[0].lat,+j[0].lon]:null}catch{return null}}
function miles(a,b){if(!a||!b)return Infinity;const R=3958.8,dLat=(b[0]-a[0])*Math.PI/180,dLng=(b[1]-a[1])*Math.PI/180,la1=a[0]*Math.PI/180,la2=b[0]*Math.PI/180;const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLng/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
async function nearestHospital(point){if(!point)return null;const rows=await Promise.all(TRAUMA.map(async h=>({...h,point:await geocode(h.address)})));return rows.filter(x=>x.point).sort((a,b)=>miles(point,a.point)-miles(point,b.point))[0]||null}
function stepText(s){const m=s.maneuver||{},name=(s.name||'').toUpperCase(),mod=(m.modifier||'').toUpperCase().replaceAll('_',' '),mi=s.distance?`${(s.distance/1609.344).toFixed(1)} MI`:'';if(m.type==='off ramp')return`Take ${name||'the next'} EXIT`;if(m.type==='on ramp'||m.type==='merge')return`Take ${name||'freeway ramp'}`;if(m.type==='turn')return`Turn ${mod||''}${name?` onto ${name}`:''}${s.distance>350?` and go ${mi}`:''}`.replace(/\s+/g,' ').trim();if(m.type==='continue'||m.type==='new name')return`Continue${name?` on ${name}`:''}${s.distance>500?` for ${mi}`:''}`;if(m.type==='arrive')return'Arrive at destination. Park as directed.';return''}
async function route(origin,dest){if(!dest)return null;try{const u=`https://router.project-osrm.org/route/v1/driving/${origin.lng},${origin.lat};${dest[1]},${dest[0]}?overview=full&geometries=geojson&steps=true`;const r=await fetch(u),j=await r.json(),rt=j.routes?.[0],steps=rt?.legs?.[0]?.steps||[];if(!rt)return null;const points=(rt.geometry?.coordinates||[]).map(c=>[c[1],c[0]]);return{origin,points,instructions:steps.filter(s=>s.distance>30||s.maneuver?.type==='arrive').map(stepText).filter(Boolean)}}catch{return null}}
function toolHref(base,show){const u=new URL(base,window.location.origin);u.searchParams.set('show',show.id);u.searchParams.set('showId',show.id);u.searchParams.set('showName',show.name||'');u.searchParams.set('fromHub','1');return u.toString()}
function PinLogo(){return <svg viewBox="0 0 74 92" aria-hidden="true"><path className="o" d="M37 3C18 3 5 17 5 36c0 22 17 40 32 53 15-13 32-31 32-53C69 17 56 3 37 3Z"/><path className="m" d="M16 39l15-13 8 7 10-10 12 14-12-8-10 10-8-7-15 7Z"/><path className="r" d="M19 69c12-14 24-18 31-27-3 14-12 22-20 31l7 8-9 2-9-14Z"/></svg>}
function Nav({show}){return <div className="cmx-nav"><a href={toolHref('https://budget.taylorscout.com',show)}>Budget</a><a href={toolHref('https://bible.taylorscout.com',show)}>Bible</a><a href={toolHref('https://calendar.taylorscout.com',show)}>Calendar</a><a href={toolHref('/waypoint',show)}>Waypoint</a></div>}
function editableProps(onBlur){return{contentEditable:true,suppressContentEditableWarning:true,onBlur:e=>onBlur(e.currentTarget.innerText.trim())}}

function StreetMap({data,onPatch,tool}){
 const ref=useRef(null),mapRef=useRef(null),markers=useRef([]),drawing=useRef(false),drawPts=useRef([]);
 const syncRoute=map=>{
  if(!map?.getStyle())return;
  const points=(data.manualRoute?.length?data.manualRoute:(data.routes?.[0]?.points||[])).map(p=>[p[1],p[0]]);
  const geo={type:'Feature',geometry:{type:'LineString',coordinates:points}};
  if(map.getSource('route-line'))map.getSource('route-line').setData(geo);else if(points.length>1){map.addSource('route-line',{type:'geojson',data:geo});map.addLayer({id:'route-line',type:'line',source:'route-line',layout:{'line-join':'round','line-cap':'round'},paint:{'line-color':'#e91d2a','line-width':6,'line-opacity':1}})}
 };
 useEffect(()=>{
  if(!ref.current)return;let map;
  try{const center=data.destinationPoint||data.destPoint||data.setPoint||[34.05,-118.25];map=new maplibregl.Map({container:ref.current,style:'https://tiles.openfreemap.org/styles/bright',center:[center[1],center[0]],zoom:13.9,attributionControl:false,preserveDrawingBuffer:true});mapRef.current=map;map.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-right');map.on('load',()=>{syncRoute(map);const pts=[...(data.manualRoute||[]),...(data.callouts||[]).map(c=>c.point),data.setPoint,data.destinationPoint].filter(Boolean);if(pts.length>1){const b=new maplibregl.LngLatBounds();pts.forEach(p=>b.extend([p[1],p[0]]));map.fitBounds(b,{padding:{top:70,right:100,bottom:70,left:80},maxZoom:15.2,duration:0})}});map.on('click',e=>{if(tool!=='draw')return;const p=[e.lngLat.lat,e.lngLat.lng];const next=[...(data.manualRoute||[]),p];onPatch({manualRoute:next});drawPts.current=next});map.on('dblclick',e=>{if(tool==='draw')e.preventDefault()});}catch(e){console.error(e)}return()=>{mapRef.current=null;map?.remove()}},[data.id]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;const once=()=>syncRoute(map);if(map.loaded())once();else map.once('load',once)},[JSON.stringify(data.manualRoute),JSON.stringify(data.routes)]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;map.getCanvas().style.cursor=tool==='draw'?'crosshair':tool==='hand'?'grab':'default';if(tool==='draw')map.doubleClickZoom.disable();else map.doubleClickZoom.enable()},[tool]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;markers.current.forEach(m=>m.remove());markers.current=[];for(const c of data.callouts||[]){if(c.visible===false||!c.point)continue;const el=document.createElement('div');el.className=`cmx-callout ${String(c.type||'').toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;el.innerHTML=`<span>${c.icon||''}</span><b>${c.label||c.type}</b><i>🔗</i>`;const mk=new maplibregl.Marker({element:el,draggable:true,anchor:'bottom'}).setLngLat([c.point[1],c.point[0]]).addTo(map);mk.on('dragend',()=>{const p=mk.getLngLat();onPatch({callouts:(data.callouts||[]).map(x=>x.id===c.id?{...x,point:[p.lat,p.lng]}:x)})});el.ondblclick=()=>{const v=prompt('Edit label',c.label||c.type);if(v?.trim())onPatch({callouts:(data.callouts||[]).map(x=>x.id===c.id?{...x,label:v.trim()}:x)})};markers.current.push(mk)}return()=>markers.current.forEach(m=>m.remove())},[JSON.stringify(data.callouts)]);
 return <div className="cmx-map" ref={ref}/>;
}

function Editor({show,map,onBack,onSave,onDashboard}){
 const[d,setD]=useState(map),[tool,setTool]=useState('select'),[zoom,setZoom]=useState(100),[busy,setBusy]=useState(false),timer=useRef();
 useEffect(()=>setD(map),[map.id]);
 const patch=p=>{const next={...d,...p};setD(next);clearTimeout(timer.current);timer.current=setTimeout(()=>onSave(next,true),650)};
 const setCard=(id,p)=>patch({cards:(d.cards||[]).map(c=>c.id===id?{...c,...p}:c)});
 const addCard=type=>patch({cards:[...(d.cards||[]),{id:uid(),type,title:type,name:'',address:'',point:null}],callouts:d.callouts||[]});
 const setDestination=async card=>{if(!card?.address)return;setBusy(true);try{const point=card.point||await geocode(card.address);if(!point)throw new Error('Could not locate that address.');const routes=(await Promise.all(ORIGINS.map(o=>route(o,point)))).filter(Boolean);patch({destinationCardId:card.id,destinationPoint:point,destPoint:point,routes,directions:Object.fromEntries(routes.map(r=>[r.origin.id,r.instructions.join('\n')]))});}catch(e){alert(e.message||'Could not update directions')}finally{setBusy(false)}};
 const undoRoute=()=>patch({manualRoute:(d.manualRoute||[]).slice(0,-1)}),clearRoute=()=>patch({manualRoute:[]});
 const print=()=>{document.documentElement.classList.add('cmx-printing');setTimeout(()=>{window.print();setTimeout(()=>document.documentElement.classList.remove('cmx-printing'),300)},100)};
 const destination=(d.cards||[]).find(c=>c.id===d.destinationCardId)||(d.cards||[]).find(c=>/crew parking|basecamp/i.test(c.type))||(d.cards||[])[0];
 return <div className="cmx-app">
  <header className="cmx-top"><button className="cmx-brand" onClick={onDashboard}><PinLogo/><span><b>TAYLOR SCOUT</b><small>PRODUCTION TOOLS</small></span></button><div className="cmx-title">CREW MAPS • EDITOR</div><div className="cmx-actions"><Nav show={show}/><button className="save" onClick={()=>onSave(d)}><Save size={16}/>Save</button><button onClick={print}><Printer size={16}/>Print</button></div></header>
  <aside className="cmx-side"><h2>{show.name}</h2><small>CREW MAPS</small><button className="editor">MAP EDITOR</button><div className="cmx-side-label">EPISODES</div><div className="cmx-episode">Episode {d.episode||'—'}<ChevronDown size={15}/></div><div className="cmx-side-label">LOCATIONS (THIS EPISODE)</div><div className="cmx-side-loc active"><div><b>{d.set||d.location}</b><span>{d.setAddress||''}</span></div><MapPin size={15}/></div><div className="cmx-side-label">LAYERS</div>{[['★','Set'],['P','Basecamp / Parking'],['VIP','VIP Parking'],['—','Routes'],['A','Street Labels'],['☷','Legend']].map(([i,x])=><label className="cmx-layer" key={x}><input type="checkbox" defaultChecked/><span>{i}</span>{x}</label>)}<div className="cmx-side-label">TOOLS</div><div className="cmx-tools">{[['select',MousePointer2,'Select'],['draw',Link2,'Draw Route'],['box',SquareDashed,'Add Box'],['pin',MapPin,'Add Pin'],['text',Type,'Add Text']].map(([id,Icon,label])=><button key={id} className={tool===id?'active':''} onClick={()=>setTool(id)}><Icon size={17}/><small>{label}</small></button>)}</div><button className="cmx-dashboard" onClick={onDashboard}>Show Dashboard</button></aside>
  <main className="cmx-work"><section className="cmx-panel"><div className="cmx-panel-head"><b>{tool==='draw'?'DRAW ROUTE':'MAP ELEMENTS'}</b><button onClick={()=>setTool('select')}>×</button></div>{tool==='draw'?<><label>Route Name<input value={d.routeName||'CREW ROUTE'} onChange={e=>patch({routeName:e.target.value})}/></label><label>Line Color<input type="color" value={d.routeColor||'#e91d2a'} onChange={e=>patch({routeColor:e.target.value})}/></label><label>Line Weight<select value={d.routeWeight||6} onChange={e=>patch({routeWeight:+e.target.value})}><option>4</option><option>6</option><option>8</option><option>10</option></select></label><div className="cmx-route-actions"><button onClick={undoRoute}><Undo2 size={14}/>Undo point</button><button onClick={clearRoute}>Clear</button></div></>:<><p className="cmx-help">Edit labels, addresses, destination routing and map content without changing the locked page structure.</p></>}
   <h4>ADD LINKED DESTINATION</h4>{(d.cards||[]).filter(c=>/SET|PARKING|BASECAMP|CATERING|VIP/i.test(c.type)).map(c=><div className="cmx-dest" key={c.id}><div><b>{c.type}</b><span>{c.title||c.name}</span><small>{c.address||'Add address'}</small></div><button onClick={()=>setDestination(c)} disabled={busy}>{d.destinationCardId===c.id?'Routing Here':'Set as Destination'}</button></div>)}
   <label className="cmx-toggle">Show Directions Preview<input type="checkbox" checked={d.showDirections!==false} onChange={e=>patch({showDirections:e.target.checked})}/></label><details open><summary>MAP ELEMENTS ({(d.cards||[]).length})</summary>{(d.cards||[]).map(c=><div className="cmx-card-edit" key={c.id}><b>{c.type}</b><input value={c.title||''} onChange={e=>setCard(c.id,{title:e.target.value})}/><input value={c.address||''} placeholder="Address" onChange={e=>setCard(c.id,{address:e.target.value,point:null})}/></div>)}</details><details><summary>PAGE LAYOUT</summary><p>Layout is locked. Content remains editable.</p></details></section>
   <section className="cmx-canvas-wrap"><div className="cmx-canvasbar"><button><Undo2 size={15}/></button><button disabled><Redo2 size={15}/></button><button onClick={()=>setZoom(z=>Math.max(60,z-10))}><Minus size={15}/></button><b>{zoom}%</b><button onClick={()=>setZoom(z=>Math.min(140,z+10))}><Plus size={15}/></button><button onClick={()=>setTool('hand')}><Hand size={15}/></button><button onClick={()=>setZoom(100)}>Fit to Page</button><button className="preview" onClick={print}>Preview / Print</button></div><div className="cmx-sheet-stage"><article className="cmx-sheet" style={{'--cmx-zoom':zoom/100}}>
    <section className="cmx-left"><div className="cmx-head"><div className="cmx-showlogo">{show.logo?<img src={show.logo}/>:<b>{show.name}</b>}</div><div className="cmx-contact"><b {...editableProps(v=>patch({contact:{...(d.contact||{}),name:v}}))}>{d.contact?.name||'NAME'}</b><strong {...editableProps(v=>patch({contact:{...(d.contact||{}),phone:v}}))}>{d.contact?.phone||'NUMBER'}</strong><span {...editableProps(v=>patch({contact:{...(d.contact||{}),role:v}}))}>{d.contact?.role||'KEY ASSISTANT LOCATION'}</span></div></div><div className="cmx-set" {...editableProps(v=>patch({set:v}))}>{d.set||d.location}</div><div className="cmx-meta"><span>MAP IS CLOSE<br/>TO SCALE</span><b>{range(d)}</b><strong {...editableProps(v=>patch({mapType:v}))}>{d.mapType||'CREW'}</strong></div><div className="cmx-warning" {...editableProps(v=>patch({warning:v}))}>{d.warning||'NO CREW PARKING IN THE NEIGHBORHOOD'}</div><div className="cmx-qr"><div {...editableProps(v=>patch({qrText:v}))}>{d.qrText||`Aim the camera on your smart phone on the QR Code to pull up Google Maps link to ${destination?.type||'CREW PARKING'}`}</div><img alt="QR code" src={`https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(`https://www.google.com/maps/dir/?api=1&destination=${destination?.address||d.setAddress||''}`)}`}/></div>{d.showDirections!==false&&<div className="cmx-directions">{(d.routes||[]).map(r=><section key={r.origin.id}><h3>Directions from the {r.origin.name} to {destination?.type||'DESTINATION'}</h3><ol>{String(d.directions?.[r.origin.id]||r.instructions?.join('\n')||'').split('\n').filter(Boolean).map((x,i)=><li key={i}>{x}</li>)}</ol></section>)}</div>}<div className="cmx-hospital"><b>H</b><div><small>NEAREST LEVEL I–III TRAUMA CENTER</small><strong>{d.hospital?.name||'Add trauma center'}</strong><span>{d.hospital?.address||''}{d.hospital?.phone?` · ${d.hospital.phone}`:''}</span></div></div></section>
    <section className="cmx-right"><div className="cmx-look"><small>LOOK FOR:</small><b {...editableProps(v=>patch({signCode:v}))}>{d.signCode||'VBF'}</b><strong>➜</strong></div><div className="cmx-mapbox"><StreetMap data={d} onPatch={patch} tool={tool}/><div className="cmx-maptools"><MousePointer2/><Link2/><SquareDashed/><MapPin/><Type/></div></div><div className="cmx-bottomcards">{[0,1,2].map(i=>{const c=(d.cards||[])[i];return <div key={i}>{c?<><b {...editableProps(v=>setCard(c.id,{title:v}))}>{c.title}</b><strong {...editableProps(v=>setCard(c.id,{name:v}))}>{c.name||c.type}</strong><span {...editableProps(v=>setCard(c.id,{address:v}))}>{c.address}</span></>:<>DRAG AND DROP<br/>INFO TO BOXES</>}</div>})}</div><div className="cmx-inset"><div><b>MAP AREA</b><span>{d.location||d.set}</span></div></div></section>
   </article></div></section></main>
 </div>
}

export default function CrewMapsLockedEditor({show,onBack}){
 const[loading,setLoading]=useState(true),[error,setError]=useState(''),[events,setEvents]=useState([]),[locations,setLocations]=useState([]),[bibles,setBibles]=useState([]),[maps,setMaps]=useState([]),[eventId,setEventId]=useState(''),[mapType,setMapType]=useState('CREW'),[active,setActive]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let dead=false;(async()=>{const[cal,l,b,cm]=await Promise.all([supabase.from('tool_documents').select('payload').eq('show_id',show.id).eq('tool_key','calendar').maybeSingle(),supabase.from('production_locations').select('*').eq('show_id',show.id),supabase.from('tool_documents').select('tool_key,payload').eq('show_id',show.id).like('tool_key','bible-location:%'),supabase.from('tool_documents').select('tool_key,payload,updated_at').eq('show_id',show.id).like('tool_key','crew-map:%').order('updated_at',{ascending:false})]);if(dead)return;const bad=[cal,l,b,cm].find(x=>x.error);if(bad)setError(bad.error.message);else{const ev=(cal.data?.payload?.events||[]).filter(x=>x.eventType!=='note');setEvents(ev);setEventId(ev[0]?.id||'');setLocations((l.data||[]).filter(x=>!x.metadata?.archived_at));setBibles(b.data||[]);setMaps((cm.data||[]).map(x=>({...x.payload,toolKey:x.tool_key,updatedAt:x.updated_at})))}setLoading(false)})();return()=>{dead=true}},[show.id]);
 const event=events.find(x=>x.id===eventId)||null;const loc=event?locations.find(l=>l.id===event.locationId)||locations.find(l=>l.location_name===event.location):null;const bibleFor=id=>{const r=bibles.find(x=>x.tool_key===`bible-location:${id}`);return r?.payload?.record||r?.payload||{}};
 const grouped=useMemo(()=>{const g={};for(const e of events){const ep=e.episode||'Unassigned';(g[ep]||(g[ep]=[])).push(e)}return Object.entries(g).sort(([a],[b])=>String(a).localeCompare(String(b),undefined,{numeric:true}))},[events]);
 async function generate(){if(!event)return;setBusy(true);setError('');try{const b=bibleFor(loc?.id||event.locationId);const setAddress=loc?.address||event.address||deepFind(b,['locationAddress','setAddress','address'])||'';const crew=deepFind(b,['crewParkingAddress','crew_parking_address','parkingAddress','parking_address'])||setAddress;const basecamp=deepFind(b,['basecampAddress','base_camp_address'])||crew;const vip=deepFind(b,['vipParkingAddress','vip_parking_address'])||'';const[setPoint,crewPoint,basePoint,vipPoint]=await Promise.all([geocode(setAddress),geocode(crew),geocode(basecamp),geocode(vip)]);const destPoint=crewPoint||basePoint||setPoint;if(!destPoint)throw new Error('Crew Maps could not locate the destination address.');const[routes,hospital]=await Promise.all([Promise.all(ORIGINS.map(o=>route(o,destPoint))).then(x=>x.filter(Boolean)),nearestHospital(setPoint||destPoint)]);const cards=[{id:uid(),type:'SET',title:'SET',name:event.set||loc?.set_name||'',address:setAddress,point:setPoint},{id:uid(),type:'BASECAMP/CREW PARKING',title:'BASECAMP/CREW PARKING',name:'',address:basecamp||crew,point:basePoint||crewPoint},vip&&{id:uid(),type:'VIP PARKING',title:'VIP PARKING',name:'',address:vip,point:vipPoint}].filter(Boolean);const callouts=cards.filter(c=>c.point).map(c=>({id:uid(),cardId:c.id,type:c.type,label:c.title,icon:c.type==='SET'?'★':c.type.includes('VIP')?'VIP':'P',point:c.point,visible:true}));const m={id:uid(),episode:event.episode||loc?.episode_name||'',mapType,location:event.location||loc?.location_name||'LOCATION',set:event.set||loc?.set_name||'',shootStart:event.shootStart||'',shootEnd:event.shootEnd||event.shootStart||'',setAddress,destinationCardId:cards[1]?.id||cards[0]?.id,destinationPoint:destPoint,destPoint,routes,directions:Object.fromEntries(routes.map(r=>[r.origin.id,r.instructions.join('\n')])),signCode:'VBF',warning:'NO CREW PARKING IN THE NEIGHBORHOOD',cards,callouts,contact:{name:deepFind(b,['locationManager','keyName','keyAssistant','contactName'])||'',phone:deepFind(b,['locationManagerPhone','keyPhone','contactPhone'])||'',role:'KEY ASSISTANT LOCATION'},hospital,manualRoute:[],showDirections:true,createdAt:new Date().toISOString()};await save(m);setActive(m)}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
 async function save(m,silent=false){const{data:{user}}=await supabase.auth.getUser();const{error:e}=await supabase.from('tool_documents').upsert({show_id:show.id,tool_key:`crew-map:${m.id}`,payload:m,updated_by:user?.id||null},{onConflict:'show_id,tool_key'});if(e){if(!silent)alert(e.message);throw e}setMaps(v=>[m,...v.filter(x=>x.id!==m.id)]);if(!silent)setActive(m)}
 if(active)return <Editor show={show} map={active} onBack={()=>setActive(null)} onSave={save} onDashboard={onBack}/>;
 return <div className="cmx-home"><header><button onClick={onBack}><PinLogo/><span><b>TAYLOR SCOUT</b><small>CREW MAPS</small></span></button><strong>{show.name}</strong></header><main><button className="cmx-home-back" onClick={onBack}><ArrowLeft size={15}/>Show Dashboard</button><h1>Crew Maps</h1><p>Choose a scheduled location. Locations are separated by episode.</p>{error&&<div className="cmx-error">{error}</div>}<section className="cmx-generator"><label><small>CALENDAR / LOCATION</small><div><select value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">Select…</option>{grouped.map(([ep,items])=><optgroup key={ep} label={`Episode ${ep}`}>{items.map(e=><option key={e.id} value={e.id}>{e.location||e.set} — {e.set||''} — {range(e)}</option>)}</optgroup>)}</select><ChevronDown/></div></label><label><small>MAP TYPE</small><div><select value={mapType} onChange={e=>setMapType(e.target.value)}>{MAP_TYPES.map(x=><option key={x}>{x}</option>)}</select><ChevronDown/></div></label><button disabled={!event||busy} onClick={generate}>{busy?'Generating…':'Generate Map'}</button></section><section className="cmx-saved"><h2>Saved Maps</h2>{loading?<p>Loading…</p>:maps.map(m=><button key={m.id} onClick={()=>setActive(m)}><b>{m.location||m.set}</b><span>Episode {m.episode||'—'} · {m.mapType} · {range(m)}</span></button>)}</section></main></div>
}
